### ISSUE TITLE
Date Picker Configuration Issues

### ISSUE THREAD

**Issue by creator-007** [gauravxor/indian-tourism-frontend#1]
During the user signup process, the date picker has two distinct issues:

1. **Date Selection Beyond Current Date:** Presently, users can select dates beyond the current date, which is logically incorrect.
2. **Lack of Date Range Specification**: There is a necessity to enforce a date range to ensure users meet a minimum age requirement for registration.

**Comment by walgaur** [comment]
Hi @creator-007,
Thanks for pointing out the issue.

I am working on an update for the frontend of the application and it is under active development. This issue will be addressed there.
However, it's important to note that alongside this update, I'm managing other commitments and ongoing tasks. This might cause a slight delay in the release.

Thank you.

**Comment by walgaur** [comment]
Hi @creator-007,
After some research, I have found that it is not necessary to enforce a minimum age requirement to book tickets.

The application does not contain any content that require viewer discretion. 
Also to book tickets, as long as a user is able to make payment, they should be good to go without any restriction.

The other issue of date selection beyond current date is valid one, and will be resolved soon.

**Comment by walgaur** [comment]
Issue is fixed in commit 53699796600088de837ab4035da36d8bf3d5d437.
